# Generated by Django 6.0.3 on 2026-03-04 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PLAYING', 'Playing'), ('FINISHED', 'Finished')], default='WAITING', max_length=10)),
                ('fen', models.TextField(default='startpos')),
                ('moves', models.TextField(blank=True, default='')),
                ('black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_games', to=settings.AUTH_USER_MODEL)),
                ('white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
