# Generated by Django 6.0.3 on 2026-03-04 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0002_game_black_time_game_last_move_ts_game_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draw_offered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
